image:
- Visual Studio 2017
# - Ubuntu  Cmake 3.5.1 !?

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 3

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: mklink %MINGW_DIR%\make.exe %MINGW_DIR%\mingw32-make.exe

- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends gfortran cmake make > /dev/null

install:
- cd bin
- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
- sh: cmake ..

- cmake --build . --target install

test_script:
- ctest -V

