language: generic
fast_finish: true

os:
  - linux
  
group: travis_latest

env: FC=gfortran

git:
  depth: 3

addons:
  apt:
    packages: gfortran

install: 
  - make

script:
  - ./snpcal 2018
  - diff snpcal2018.txt ref/snpcal2018.txt

