language: generic
group: travis_latest

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages: gfortran

matrix:
  include:
  - os: linux
  - os: osx
    before_install:
    - brew install gcc > /dev/null
  - os: windows
    language: sh
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .

install:
- cd build
- cmake ..
- cmake --build .

script: ctest --output-on-failure

