language: generic

os:
  - linux
  - osx
  
group: travis_latest

env: FC=gfortran

git:
  depth: 3
  quiet: true

addons:
  apt:
    packages: gfortran
    
before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true > /dev/null;
      brew link --overwrite gcc > /dev/null;
      export FC=gfortran;
    fi

install: 
  - cd build
  - cmake ..
  - cmake --build .
  
script:
  - ctest -V

