name: ci_cmake

on:
  push:
    paths:
      - "**.f"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default
